@Kindergarden.WebApi_HostAddress = http://localhost:5274

GET {{Kindergarden.WebApi_HostAddress}}/api/v1/Weather/
Accept: application/json
###

GET {{Kindergarden.WebApi_HostAddress}}/api/v2/weather/
Accept: application/json
###
